name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint .
      - name: Type check
        run: npx tsc --noEmit
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Run migrations
        run: npm run dev:migrate

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Deploy to server via SSH/rsync
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/aiqedge-smtp
            rsync -avz --delete ./dist/ ~/aiqedge-smtp/dist/
            rsync -avz --delete ./package.json ./node_modules ./ecosystem.config.js ./tsconfig.json ./README.md ~/aiqedge-smtp/
            cd ~/aiqedge-smtp
            npm install --production
            sudo systemctl restart aiqedge-smtp || true
